name: deploy to amazon linux
on:  [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
       - name: ssh into ec2 and run command
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.SSH_KEY }}
           script: 
             echo "---STARTING NGINX DEPLOYMENT--"
             sudo docker run -d --name my-web-server -p 80:80 nginx 
             
             echo "---check status--"
             sudo docker ps
               
          
