
             
               
          
name: ci cd with environments
on:
  push:
    branches: [main]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: build docker image
        run: echo "building ur docker image"
  deploy-dev:
    needs: build-and-push
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: deploying to dev server
        run: echo "deplloying to development envi"
  deploy-prod:
    needs: deploy-dev
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: final deploy to ec2
        run: echo "deploying to ur production server"
