name: learning variables and secrets
on:  [workflow_dispatch]
jobs:
  secrets_check:
     runs-on: ubuntu-latest
     steps:
       - name: dummy login attempt
         run: |
           echo "connecting to server"
           echo "attempting to connect as user: ${{ secrets.SERVER_USER }}"

          
